force-app/main/default/objects/Log__e/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <defaultValue>&apos;DEBUG&apos;</defaultValue>
    <label>Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Limits__c.field-meta.xml
<CustomField>
    <fullName>Limits__c</fullName>
    <description>https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Limits</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>Notification_Email__c</fullName>
    <label>Notification Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <description>Quiddity value of the current Request object
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Request.htm</description>
    <label>Quiddity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Request_Id__c</fullName>
    <description>Apex Request Id
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Request.htm</description>
    <label>Request Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Running_User_ID__c.field-meta.xml
<CustomField>
    <fullName>Running_User_ID__c</fullName>
    <label>Running User ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Time_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Time_Stamp__c</fullName>
    <label>Time Stamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Salesforce_Log__c/Salesforce_Log__c.object-meta.xml
<CustomObject>
    <description>A custom object to hold logs created from various apex classes.</description>
    <label>Salesforce Log</label>
    <nameField>
        <displayFormat>L-{0}</displayFormat>
        <label>Custom Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_Log__c/fields/Limits__c.field-meta.xml
<CustomField>
    <fullName>Limits__c</fullName>
    <description>https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Limits</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Log__c/fields/Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>Notification_Email__c</fullName>
    <label>Notification Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Salesforce_Log__c/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <description>Quiddity value of the current Request object
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Request.htm</description>
    <label>Quiddity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Salesforce_Log__c/fields/Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Request_Id__c</fullName>
    <description>Apex Request Id
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Request.htm</description>
    <label>Request Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Salesforce_Log__c/fields/Running_User_ID__c.field-meta.xml
<CustomField>
    <fullName>Running_User_ID__c</fullName>
    <description>Since all Logs are created by &apos;Automated Process&apos; user this field is used to store Id of a running user when a log event was fired.</description>
    <inlineHelpText>Used to store Id of a running user when the Log was created.</inlineHelpText>
    <label>Running User ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Salesforce_Log_Setting__mdt/Salesforce_Log_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Salesforce Log Setting</label>
    <pluralLabel>Salesforce Log Settings</pluralLabel>
</CustomObject>

force-app/main/default/classes/LogService.cls
public inherited sharing class LogService {
    /**
    * Creates 'Salesforce Log' records based on Log__e platform events.
    *
    * @param eventLogs map of Log__e platform events
    */
    public static void recordSalesforceLogs(Map<Id,Log__e> eventLogs) {
        List<Salesforce_Log__c> sfLogs = new List<Salesforce_Log__c>();
        Map<String, Salesforce_Log_Setting__mdt> settingsByLocation = getSalesforceLogSettings();   

        try{ 
            for(Log__e eventLog : eventLogs.values()) {
                // Check whether we have Salesforce_Log_Setting__mdt record for the location defined. Location__c
                // If yes, create only logs with respective logging level. Otherwise the logging level is not checked and logs are created.
                if(settingsByLocation.containsKey(eventLog.Location__c)){
                    if(eventLog.Level__c == 'DEBUG' && settingsByLocation.get(eventLog.Location__c).DEBUG__c == true
                        || eventLog.Level__c == 'ERROR' && settingsByLocation.get(eventLog.Location__c).ERROR__c == true){
                            sfLogs.add(prepareSalesforceLogRecord(eventLog));
                    }  
                } else {
                    sfLogs.add(prepareSalesforceLogRecord(eventLog));
                }
            }
            insert sfLogs;
        } 
        catch (Exception e){
            Logger.log(Logger.Level.ERROR, 'Something fatal has occurred and hence failed to create Salesforce Log records.', 'LogService', e);
        }
    }

    private static Salesforce_Log__c prepareSalesforceLogRecord(Log__e eventLog){
        Salesforce_Log__c log = new Salesforce_Log__c();
        log.Running_User_ID__c = eventLog.Running_User_ID__c;
        log.Level__c = eventLog.Level__c;
        log.Location__c = eventLog.Location__c;
        log.Related_Record_ID__c = eventLog.Related_Record_ID__c;
        log.Message__c = eventLog.Message__c;
        log.Time_Stamp__c = eventLog.Time_Stamp__c;
        log.Exception_Type__c = eventLog.Exception_Type__c;
        log.Exception_Stack_Trace__c = eventLog.Exception_Stack_Trace__c;
        log.Exception_Message__c = eventLog.Exception_Message__c;
        log.Quiddity__c = eventLog.Quiddity__c;
        log.Request_Id__c = eventLog.Request_Id__c;
        log.Limits__c = eventLog.Limits__c;

        if (String.isNotBlank( eventLog.Notification_Email__c )){
            if (Utility.isValidEmail( eventLog.Notification_Email__c )) {
                log.Notification_Email__c = eventLog.Notification_Email__c; 
            } else {
                log.Message__c = 'Email address for notification is not in correct format! \n\n' + log.Message__c;
            }
        }

        return log;
    }

    private static Map<String, Salesforce_Log_Setting__mdt> getSalesforceLogSettings(){
        Map<String, Salesforce_Log_Setting__mdt> logSettings = new Map<String, Salesforce_Log_Setting__mdt>(Salesforce_Log_Setting__mdt.getAll());
        Map<String, Salesforce_Log_Setting__mdt> settingsByLocation = new Map<String, Salesforce_Log_Setting__mdt>();

        for(Salesforce_Log_Setting__mdt setting : logSettings.values()){
            settingsByLocation.put(setting.Location__c, setting);
        }
        return settingsByLocation;
    }
}