force-app/main/default/objects/Log__e/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <defaultValue>&apos;DEBUG&apos;</defaultValue>
    <label>Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Limits__c.field-meta.xml
<CustomField>
    <fullName>Limits__c</fullName>
    <description>https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Limits</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>Notification_Email__c</fullName>
    <label>Notification Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <description>Quiddity value of the current Request object
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Request.htm</description>
    <label>Quiddity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Request_Id__c</fullName>
    <description>Apex Request Id
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Request.htm</description>
    <label>Request Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Running_User_ID__c.field-meta.xml
<CustomField>
    <fullName>Running_User_ID__c</fullName>
    <label>Running User ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Time_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Time_Stamp__c</fullName>
    <label>Time Stamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Salesforce_Log__c/Salesforce_Log__c.object-meta.xml
<CustomObject>
    <description>A custom object to hold logs created from various apex classes.</description>
    <label>Salesforce Log</label>
    <nameField>
        <displayFormat>L-{0}</displayFormat>
        <label>Custom Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_Log__c/fields/Limits__c.field-meta.xml
<CustomField>
    <fullName>Limits__c</fullName>
    <description>https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm</description>
    <label>Limits</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Log__c/fields/Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>Notification_Email__c</fullName>
    <label>Notification Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Salesforce_Log__c/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <description>Quiddity value of the current Request object
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Request.htm</description>
    <label>Quiddity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Salesforce_Log__c/fields/Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Request_Id__c</fullName>
    <description>Apex Request Id
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Request.htm</description>
    <label>Request Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Salesforce_Log__c/fields/Running_User_ID__c.field-meta.xml
<CustomField>
    <fullName>Running_User_ID__c</fullName>
    <description>Since all Logs are created by &apos;Automated Process&apos; user this field is used to store Id of a running user when a log event was fired.</description>
    <inlineHelpText>Used to store Id of a running user when the Log was created.</inlineHelpText>
    <label>Running User ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Logger.cls
public with sharing class Logger {
    public enum Level {
        ERROR,
        DEBUG
    }

    /**
    * @description Log errors in bulk which are direct results of a DML
    * @param developerErrorMessage developer added message to identify the issue better
    * @param results List of delete results
    * @param objectList List of objects used in DML
    * @param location Salesforce_Log__c location
    */
    public static void LogErrors(String developerErrorMessage, List<Database.DeleteResult> results, List<SObject> objectList, String location) {
        Integer index = 0;
        Integer errorIds = 0;
        Map<String, SObject> errorMap = new Map<String, SObject>();
        for (Database.DeleteResult dr : results) {
            if (!dr.isSuccess() && errorMap.size() < 1000) {
                for (Database.Error error : dr.getErrors()) {
                    String deleteResultErrMsg = error.getMessage();
                    if (!errorMap.containsKey(deleteResultErrMsg)) {
                        errorMap.put(deleteResultErrMsg, objectList[index]);
                    }
                    errorIds++;
                }
            }
            index++;
        }

        List<LogDetail> errorDetails = new List<LogDetail>();
        for (String deleteResultErrMsg : errorMap.keySet()) {
            String errorMessage = deleteResultErrMsg;
            if (String.isNotBlank(developerErrorMessage)) {
                errorMessage = developerErrorMessage + ': ' + errorMessage;
            }
            errorDetails.add(new LogDetail(Logger.Level.ERROR, errorMessage, location, null, errorMap.get(deleteResultErrMsg)));
        }

        Logger.log(errorDetails);
    }

    /**
    * @description Log errors in bulk which are direct results of a DML
    * @param developerErrorMessage developer added message to identify the issue better
    * @param results List of save results
    * @param objectList List of objects used in DML
    * @param location Salesforce_Log__c location
    */
    public static void LogErrors(String developerErrorMessage, List<Database.SaveResult> results, List<SObject> objectList, String location) {
        Integer index = 0;
        Integer errorIds = 0;
        Map<String, SObject> errorMap = new Map<String, SObject>();
        for (Database.SaveResult sr : results) {
            if (!sr.isSuccess() && errorMap.size() < 1000) {
                for (Database.Error error : sr.getErrors()) {
                    String saveResultErrMsg = error.getMessage();
                    if (!errorMap.containsKey(saveResultErrMsg)) {
                        errorMap.put(saveResultErrMsg, objectList[index]);
                    }
                    errorIds++;
                }
            }
            index++;
        }

        List<LogDetail> errorDetails = new List<LogDetail>();
        for (String saveResultErrMsg : errorMap.keySet()) {
            String errorMessage = saveResultErrMsg;
            if (String.isNotBlank(developerErrorMessage)) {
                errorMessage = developerErrorMessage + ': ' + errorMessage;
            }
            errorDetails.add(new LogDetail(Logger.Level.ERROR, errorMessage, location, null, errorMap.get(saveResultErrMsg)));
        }

        Logger.log(errorDetails);
    }

    public class LogDetail {
        public Level logLevel;
        public String message;
        public String location;
        public Exception e { get; set; }
        public String relatedRecordId { get; set; }
        public String notificationEmail { get; set; }

        public LogDetail(Level logLevel,
                String message,
                String location,
                Exception e,
                SObject relatedRecord,
                String notificationEmail) {
            this.logLevel = logLevel;
            this.message = message + ',\nRecord: ' + String.valueOf(relatedRecord);
            this.location = location;
            this.e = e;
            this.relatedRecordId = relatedRecord?.Id;
            this.notificationEmail = notificationEmail;
        }

        public LogDetail(Level logLevel,
                String message,
                String location,
                Exception e,
                SObject relatedRecord) {
            this.logLevel = logLevel;
            this.message = message + ',\nRecord: ' + String.valueOf(relatedRecord);
            this.location = location;
            this.e = e;
            this.relatedRecordId = relatedRecord?.Id;
        }

        public LogDetail(Level logLevel,
                String message,
                String location,
                Exception e) {
            this.logLevel = logLevel;
            this.message = message;
            this.location = location;
            this.e = e;
            this.relatedRecordId = '';
            this.notificationEmail = '';
        }

        public LogDetail(Level logLevel,
                String message,
                String location) {
            this.logLevel = logLevel;
            this.message = message;
            this.location = location;
            this.e = null;
            this.relatedRecordId = '';
            this.notificationEmail = '';
        }
    }

    public static void log(List<LogDetail> logDetails) {
        List<Log__e> logEvents = new List<Log__e>();

        for (LogDetail detail : logDetails) {
            logEvents.add(createLogEvent(detail.logLevel,
                    detail.message,
                    detail.location,
                    detail.e,
                    detail.relatedRecordId,
                    detail.notificationEmail));
        }
        EventBus.publish(logEvents);
    }

    public static void log(Level logLevel, String message, String location) {
        log(logLevel, message, location, null, '', '');
    }

    public static void log(Level logLevel, String message, String location, Exception e) {
        log(logLevel, message, location, e, '', '');
    }

    public static void log(Level logLevel, String message, String location, Exception e, String relatedRecordId) {
        emit(logLevel, message, location, e, relatedRecordId, '');
    }

    public static void log(Level logLevel, String message, String location, String relatedRecordId) {
        emit(logLevel, message, location, null, relatedRecordId, '');
    }

    public static void log(Level logLevel, String message, String location, Exception e, String relatedRecordId, String notificationEmail) {
        emit(logLevel, message, location, e, relatedRecordId, notificationEmail);
    }

    private static void emit(Level logLevel, String message, String location, Exception e, String relatedRecordId, String notificationEmail) {
        Log__e currentEvent = new Log__e();

        currentEvent = createLogEvent(logLevel, message, location, e, relatedRecordId, notificationEmail);
        EventBus.publish(currentEvent);
    }

    private static Log__e createLogEvent(Level logLevel, String message, String logLocation, Exception e, String relatedRecordId, String notificationEmail) {
        Log__e newEvent = new Log__e();
        newEvent.Related_Record_ID__c = relatedRecordId;
        newEvent.Message__c = Utility.safeAbbreviate(message, Schema.SObjectType.Log__e.fields.Message__c.getLength());
        newEvent.Notification_Email__c = notificationEmail;
        newEvent.Running_User_ID__c = UserInfo.getUserId();
        newEvent.Level__c = logLevel.name();
        newEvent.Time_Stamp__c = System.now();
        newEvent.Location__c = logLocation;

        Request reqInfo = Request.getCurrent();
        newEvent.Request_Id__c = reqInfo.getRequestId();
        newEvent.Quiddity__c = reqInfo.getQuiddity().name();

        List<LimitService.LimitDTO> limits = new List<LimitService.LimitDTO>{
                LimitService.getLimit(LimitService.LimitName.CPU_TIME),
                LimitService.getLimit(LimitService.LimitName.SOQL_QUERIES)
        };
        newEvent.Limits__c = Utility.safeAbbreviate(JSON.serialize(limits), SObjectType.Log__e.fields.Limits__c.length);

        if (e != null) {
            newEvent.Exception_Type__c = e.getTypeName();
            newEvent.Exception_Stack_Trace__c = e.getStackTraceString();
            newEvent.Exception_Message__c = e.getMessage();
        }
        return newEvent;
    }
}